name: TotalFreedomMod
version: 0.1
description: TotalFreedomMod Remastered
author: Telesphoreo
main: com.fusenetworks.fuse.Fuse
commands:
  admin:
    description: Manage admins
    usage: /<command> <list | add <player> | remove <player> | setrank <player> <rank>>
  gtfo:
    description: Bans a player
    usage: /<command> <player> <reason>
  list:
    description: See a list of players online
    usage: /<command>
  op:
    description: Op a player
    usage: /<command> <player>
  totalfreedommod:
    description: Shows information about TotalFreedomMod
    usage: /<command>
    aliases: tfm
  unban:
    description: Unbans a player
    usage: /<command> <player>